### ISSUE TITLE
Issue with OAuth2-related destination auth methods

### ISSUE THREAD

**Issue by alexluong** [hookdeck/hookdeck-api-schema#34]
Hi there, I'm working on the Terraform provider and discovered some inconsistencies between the dashboard and the OpenAPI schema. The issue is specifically related to the 2 entities [`DestinationAuthMethodOAuth2AuthorizationCodeConfig`](https://github.com/hookdeck/hookdeck-api-schema/blob/a5eada16b5ee9f3a6d3f3095ba5238a39c5bdf7f/fern/openapi/openapi.json#L1122C8-L1165) and [`DestinationAuthMethodOAuth2ClientCredentialsConfig`](https://github.com/hookdeck/hookdeck-api-schema/blob/a5eada16b5ee9f3a6d3f3095ba5238a39c5bdf7f/fern/openapi/openapi.json#L1071-L1100)

The issue is the `authentication_type` attribute. In the dashboard, it belongs to `OAuth2 Client Credentials` but in the OpenAPI schema it's part of `OAuth2 Authorization Code` instead.

When interacting with `authentication_type` on the dashboard, it seems this field is not persisted either. Could be a UI issue instead?

https://github.com/hookdeck/hookdeck-api-schema/assets/26750127/8576c5f8-e7d0-43bb-ae4c-363e598ceedd

**Comment by jmnavarro** [comment]
Hey @alexluong !

We've just pushed the fix, it will be deployed today!

**Comment by alexluong** [comment]
Sounds great @jmnavarro! Can you clarify what the correct setup is? I assume `authentication_type` is a part of "OAuth2 Authorization Code" then?

**Comment by jmnavarro** [comment]
No, `authentication_type` works with "Client credentials" flow. The "Authorization Code" flow is still partially supported and not available in the UI.

Most of the cases, authorization type must be `Basic` (the default) but some servers out there require a `Bearer` token instead of `Basic` header.

**Comment by alexluong** [comment]
Gotcha, in that case are you also updating the OpenAPI schema and Go SDK as well?

**Comment by jmnavarro** [comment]
Yes, schemas are updated. They will be reflected as soon as we finish the deploy.

Re the SDKs, I think they're autogenerated based on the published schemas. Do you know about this @leggetter ?

**Comment by leggetter** [comment]
> Yes, schemas are updated. They will be reflected as soon as we finish the deploy.
> 
> Re the SDKs, I think they're autogenerated based on the published schemas. Do you know about this @leggetter ?

As soon as the APIs are live we'll get an automatic PR agains the schema in this repo. Once merged we can auto-generate Go and TypeScript SDKs using the GitHub Actions 👍

**Comment by jmnavarro** [comment]
everything is up & running!

Thanks for the detailed report @alexluong !
