### ISSUE TITLE
Search connection by source / destination IDs array

### ISSUE THREAD

**Issue by alexluong** [hookdeck/hookdeck-api-schema#41]
Hi folks, I see a potential issue with the generator where in `ConnectionListRequest`, the `source_id` and `destination_id` options accept either a string or an array of strings but the generated SDKs only support string option only.

Some references:

- [OpenAPI schema](https://github.com/hookdeck/hookdeck-api-schema/blob/6b186d898796d2e5c60de6f40664bd3ad055ad07/fern/openapi/openapi.json#L18035-L18074)
- [Go SDK](https://github.com/hookdeck/hookdeck-go-sdk/blob/f52651732661e74bf7feb84f4470e0fc50289dd1/connection.go#L38-L39)
- [TypeScript SDK](https://github.com/hookdeck/hookdeck-typescript-sdk/blob/fe5971def8b7f761e3e2d1987dbb8b0f504d45af/src/api/resources/connection/client/requests/ConnectionListRequest.ts#L65-L66)

This is just one instance, and I see this issue in a few other cases as well.

I have a use case where I'd like to query connections by a list of source IDs and this seems to be a blocker. Can you help take a look and see how I can go about this?

**Comment by amckinney** [comment]
Hey @alexluong, this is a feature gap with query parameter lists, so we'll work on a fix!

In the meantime (to unblock your use case), you can still use the API by formatting the `string` with multiple values yourself. As I understand it, the query parameters are comma-delimited, so you can do the following:

```go
sourceIds := []string{
  "id_123",
  "id_456",
  "id_789",
}
request := hookdeck.ConnectionListRequest{
  DestinationId: hookdeck.String("id_xyz"),                    // Use a single value.
  SourceId:      hookdeck.String(strings.Join(sourceIds, ",")) // Use multiple values.
}
```

I know this is a little less than ideal for now, but let us know if that works for you!

**Comment by alexluong** [comment]
Thanks for getting back to me @amckinney 

> In the meantime (to unblock your use case), you can still use the API by formatting the string with multiple values yourself. As I understand it, the query parameters are comma-delimited

I don't think this is the case. I tried making API request with this but it doesn't seem to work. For example:

```
https://api.hookdeck.com/2024-03-01/connections?source_id=source-1,source-2
--> this doesn't work

https://api.hookdeck.com/2024-03-01/connections?source_id=source-1&source_id=source-2
--> this works
```

Pinging @leggetter / @alexbouchardd if you think we should support the comma-delimitied use case from the API side?

**Comment by alexluong** [comment]
@amckinney Unfortunately it seems the SDK encodes the request payload so that when using your snippet, this is the resulted request:

```
https://api.hookdeck.com/2024-03-01/sources?name=source-1%26source_id%3Dsource-3
```

**Comment by amckinney** [comment]
Gah, I forgot that the `&` would be URL-encoded (which is what we want in general) - sorry for the failed attempts at a workaround.

Fortunately, we were able to get a fix out for your use case, so all those parameters will be correctly recognized as an array of values. We tee'd up an upgrade PR in https://github.com/hookdeck/hookdeck-api-schema/pull/42, so feel free to merge and re-release the SDKs to get the fix!

Moving forward, it would be a good idea to explicitly configure the `explode: true` parameter for all of the relevant query parameters that use that format. This is especially true if you ever plan to support other query formats (e.g. comma-separated values, etc).

**Comment by alexluong** [comment]
Awesome! @leggetter can you help take a look at #42?

Pinging @alexbouchardd here if you can look into this `explode: true` thingy here for the OpenAPI schema

**Comment by alexluong** [comment]
Hi folks, I just wanted to follow up on this a bit. I'm using the new Go SDK v.0.4.1 and the ID query has been resolved but the other fields query are still not handled correctly it seems.

For example, when querying sources by `name`, this is the OpenAPI schema for that query: https://github.com/hookdeck/hookdeck-api-schema/blob/b2021921ef93db0da67f5e9f217d6620f5c33ce2/fern/openapi/openapi.json#L16313-L16371

However, in the generated SDK, I can only pass a string instead of an array: https://github.com/hookdeck/hookdeck-go-sdk/blob/9555ec315405c6742d11166b87356163068ae6a9/source.go#L23. I assume this is because there's also the object syntax that Fern may not have accounted for?

Can you help take a look? Thanks! @amckinney @leggetter

**Comment by leggetter** [comment]
@amckinney any thoughts on the above not being an array?
